### ISSUE TITLE
数据包的自定义维度似乎会导致无法启动

### ISSUE THREAD

**Issue by MATRIX-feather** [LuminolMC/Luminol#11]
### 描述你希望添加的功能。 Describe the feature you'd like.

rt, 希望可以支持数据包添加的自定义维度 :)

### 其他 Other

测试时用的数据包：
[fomwt.zip](https://github.com/LuminolMC/Luminol/files/15039190/fomwt.zip)

当前luminol和上游folia在初始化这些世界时均会抛`Scheduling chunk load off-main`：
```
[18:31:15 ERROR]: Thread Region Scheduler Thread #1 failed main thread check: Scheduling chunk load off-main
java.lang.Throwable: null
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:71) ~[luminol-1.20.4.jar:git-Luminol-"c06f539"]
        at net.minecraft.server.level.ServerChunkCache.getChunkFutureMainThread(ServerChunkCache.java:293) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:223) ~[?:?]
        at net.minecraft.world.level.Level.getChunk(Level.java:921) ~[?:?]
        at net.minecraft.world.level.Level.getChunk(Level.java:860) ~[?:?]
        at net.minecraft.server.level.PlayerRespawnLogic.getOverworldRespawnPos(PlayerRespawnLogic.java:18) ~[?:?]
        at net.minecraft.server.level.PlayerRespawnLogic.getSpawnPosInChunk(PlayerRespawnLogic.java:53) ~[?:?]
        at net.minecraft.server.MinecraftServer.setInitialSpawn(MinecraftServer.java:792) ~[luminol-1.20.4.jar:git-Luminol-"c06f539"]
        at net.minecraft.server.MinecraftServer.initWorld(MinecraftServer.java:730) ~[luminol-1.20.4.jar:git-Luminol-"c06f539"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1604) ~[luminol-1.20.4.jar:git-Luminol-"c06f539"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:408) ~[luminol-1.20.4.jar:git-Luminol-"c06f539"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.4.jar:git-Luminol-"c06f539"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.4.jar:git-Luminol-"c06f539"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[18:31:16 ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Region #5 centered at chunk [0, 0] in world 'world_fomwt_dimension' failed to tick:
net.minecraft.ReportedException: Exception initializing level
        at net.minecraft.server.MinecraftServer.initWorld(MinecraftServer.java:744) ~[luminol-1.20.4.jar:git-Luminol-"c06f539"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1604) ~[luminol-1.20.4.jar:git-Luminol-"c06f539"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:408) ~[luminol-1.20.4.jar:git-Luminol-"c06f539"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.4.jar:git-Luminol-"c06f539"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.4.jar:git-Luminol-"c06f539"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalStateException: Scheduling chunk load off-main
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:72) ~[luminol-1.20.4.jar:git-Luminol-"c06f539"]
        at net.minecraft.server.level.ServerChunkCache.getChunkFutureMainThread(ServerChunkCache.java:293) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:223) ~[?:?]
        at net.minecraft.world.level.Level.getChunk(Level.java:921) ~[?:?]
        at net.minecraft.world.level.Level.getChunk(Level.java:860) ~[?:?]
        at net.minecraft.server.level.PlayerRespawnLogic.getOverworldRespawnPos(PlayerRespawnLogic.java:18) ~[?:?]
        at net.minecraft.server.level.PlayerRespawnLogic.getSpawnPosInChunk(PlayerRespawnLogic.java:53) ~[?:?]
        at net.minecraft.server.MinecraftServer.setInitialSpawn(MinecraftServer.java:792) ~[luminol-1.20.4.jar:git-Luminol-"c06f539"]
        at net.minecraft.server.MinecraftServer.initWorld(MinecraftServer.java:730) ~[luminol-1.20.4.jar:git-Luminol-"c06f539"]
        ... 5 more
```

**Comment by MrHua269** [comment]
emmm，这个是会将这个新维度的出生点设置在出生点的region外吗（距离默认出生点超过1000个方块）？（）

**Comment by MATRIX-feather** [comment]
应该是不会的吧？我没有改过什么有关出生点的设置，数据包里也没有和他有关的东西

**Comment by MrHua269** [comment]
emmm,我无法复现这个bug

**Comment by MrHua269** [comment]
> emmm,我无法复现这个bug

你安装了类似BetterRTP之类的插件了吗

**Comment by MATRIX-feather** [comment]
没有，目前只安装了这些插件：
![image](https://github.com/LuminolMC/Luminol/assets/55654482/c8ea089d-f07d-4252-8369-7ac7e390d86b)

**Comment by MrHua269** [comment]
![image](https://github.com/LuminolMC/Luminol/assets/79621885/cbde3069-1c0c-4a35-9f20-b48b4c709cd7)
无法复现

**Comment by MATRIX-feather** [comment]
我刚刚试着挪走plugins目录，发现可以成功启动，即使再装载一样的插件也可以正常使用。

可能之前遇到了某种bug吧，我再观察一段时间，看看能不能再复现一遍出来
