### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by mani1232** [LuminolMC/Luminol#22]
### 服务端版本 LuminolMC Version

latest

### 预期的行为 Expected behavior

[12:34:31 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[12:34:31 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[12:34:31 WARN]: Exception in thread "pool-48-thread-4" java.lang.NullPointerException: Cannot invoke "org.apache.commons.lang3.tuple.Pair.getLeft()" because the return value of "java.util.Map.get(Object)" is null
[12:34:31 WARN]:        at me.earthme.luminol.utils.LuminolWatchDog.runCheck(LuminolWatchDog.java:72)
[12:34:31 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[12:34:31 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[12:34:31 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[12:34:31 INFO]: [ChunkHolderManager] Saved 3559 block chunks, 1469 entity chunks, 4 poi chunks in world 'new_world' in 4.16s
[12:34:31 WARN]: Exception in thread "pool-48-thread-5" java.lang.NullPointerException: Cannot invoke "org.apache.commons.lang3.tuple.Pair.getLeft()" because the return value of "java.util.Map.get(Object)" is null
[12:34:31 WARN]:        at me.earthme.luminol.utils.LuminolWatchDog.runCheck(LuminolWatchDog.java:72)
[12:34:31 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[12:34:31 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[12:34:31 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[12:34:31 INFO]: [RegionShutdownThread] Saving chunks around region around chunk [0, 0] in world 'world'
[12:34:31 WARN]: Exception in thread "pool-48-thread-6" java.lang.NullPointerException: Cannot invoke "org.apache.commons.lang3.tuple.Pair.getLeft()" because the return value of "java.util.Map.get(Object)" is null
[12:34:31 WARN]:        at me.earthme.luminol.utils.LuminolWatchDog.runCheck(LuminolWatchDog.java:72)
[12:34:31 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[12:34:31 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[12:34:31 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[12:34:32 WARN]: Exception in thread "pool-48-thread-7" java.lang.NullPointerException: Cannot invoke "org.apache.commons.lang3.tuple.Pair.getLeft()" because the return value of "java.util.Map.get(Object)" is null
[12:34:32 WARN]:        at me.earthme.luminol.utils.LuminolWatchDog.runCheck(LuminolWatchDog.java:72)
[12:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[12:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[12:34:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[12:34:32 WARN]: Exception in thread "pool-48-thread-8" java.lang.NullPointerException: Cannot invoke "org.apache.commons.lang3.tuple.Pair.getLeft()" because the return value of "java.util.Map.get(Object)" is null
[12:34:32 WARN]:        at me.earthme.luminol.utils.LuminolWatchDog.runCheck(LuminolWatchDog.java:72)
[12:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[12:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[12:34:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[12:34:32 WARN]: Exception in thread "pool-48-thread-9" java.lang.NullPointerException: Cannot invoke "org.apache.commons.lang3.tuple.Pair.getLeft()" because the return value of "java.util.Map.get(Object)" is null
[12:34:32 WARN]:        at me.earthme.luminol.utils.LuminolWatchDog.runCheck(LuminolWatchDog.java:72)
[12:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[12:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[12:34:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[12:34:32 WARN]: Exception in thread "pool-48-thread-10" java.lang.NullPointerException: Cannot invoke "org.apache.commons.lang3.tuple.Pair.getLeft()" because the return value of "java.util.Map.get(Object)" is null
[12:34:32 WARN]:        at me.earthme.luminol.utils.LuminolWatchDog.runCheck(LuminolWatchDog.java:72)
[12:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[12:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[12:34:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[12:34:32 WARN]: Exception in thread "pool-48-thread-11" java.lang.NullPointerException: Cannot invoke "org.apache.commons.lang3.tuple.Pair.getLeft()" because the return value of "java.util.Map.get(Object)" is null
[12:34:32 WARN]:        at me.earthme.luminol.utils.LuminolWatchDog.runCheck(LuminolWatchDog.java:72)
[12:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[12:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[12:34:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[12:34:32 WARN]: Exception in thread "pool-48-thread-12" java.lang.NullPointerException: Cannot invoke "org.apache.commons.lang3.tuple.Pair.getLeft()" because the return value of "java.util.Map.get(Object)" is null
[12:34:32 WARN]:        at me.earthme.luminol.utils.LuminolWatchDog.runCheck(LuminolWatchDog.java:72)
[12:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[12:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[12:34:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[12:34:32 WARN]: Exception in thread "pool-48-thread-13" java.lang.NullPointerException: Cannot invoke "org.apache.commons.lang3.tuple.Pair.getLeft()" because the return value of "java.util.Map.get(Object)" is null
[12:34:32 WARN]:        at me.earthme.luminol.utils.LuminolWatchDog.runCheck(LuminolWatchDog.java:72)
[12:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[12:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[12:34:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[12:34:32 WARN]: Exception in thread "pool-48-thread-14" java.lang.NullPointerException: Cannot invoke "org.apache.commons.lang3.tuple.Pair.getLeft()" because the return value of "java.util.Map.get(Object)" is null
[12:34:32 WARN]:        at me.earthme.luminol.utils.LuminolWatchDog.runCheck(LuminolWatchDog.java:72)
[12:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[12:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[12:34:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[12:34:32 WARN]: Exception in thread "pool-48-thread-15" java.lang.NullPointerException: Cannot invoke "org.apache.commons.lang3.tuple.Pair.getLeft()" because the return value of "java.util.Map.get(Object)" is null
[12:34:32 WARN]:        at me.earthme.luminol.utils.LuminolWatchDog.runCheck(LuminolWatchDog.java:72)
[12:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[12:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[12:34:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[12:34:32 WARN]: Exception in thread "pool-48-thread-16" java.lang.NullPointerException: Cannot invoke "org.apache.commons.lang3.tuple.Pair.getLeft()" because the return value of "java.util.Map.get(Object)" is null
[12:34:32 WARN]:        at me.earthme.luminol.utils.LuminolWatchDog.runCheck(LuminolWatchDog.java:72)
[12:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[12:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[12:34:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[12:34:32 WARN]: Exception in thread "pool-48-thread-17" java.lang.NullPointerException: Cannot invoke "org.apache.commons.lang3.tuple.Pair.getLeft()" because the return value of "java.util.Map.get(Object)" is null
[12:34:32 WARN]:        at me.earthme.luminol.utils.LuminolWatchDog.runCheck(LuminolWatchDog.java:72)
[12:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[12:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[12:34:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[12:34:32 WARN]: Exception in thread "pool-48-thread-18" java.lang.NullPointerException: Cannot invoke "org.apache.commons.lang3.tuple.Pair.getLeft()" because the return value of "java.util.Map.get(Object)" is null
[12:34:32 WARN]:        at me.earthme.luminol.utils.LuminolWatchDog.runCheck(LuminolWatchDog.java:72)
[12:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[12:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[12:34:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[12:34:32 WARN]: Exception in thread "pool-48-thread-19" java.lang.NullPointerException: Cannot invoke "org.apache.commons.lang3.tuple.Pair.getLeft()" because the return value of "java.util.Map.get(Object)" is null
[12:34:32 WARN]:        at me.earthme.luminol.utils.LuminolWatchDog.runCheck(LuminolWatchDog.java:72)
[12:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[12:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[12:34:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[12:34:32 WARN]: Exception in thread "pool-48-thread-20" java.lang.NullPointerException: Cannot invoke "org.apache.commons.lang3.tuple.Pair.getLeft()" because the return value of "java.util.Map.get(Object)" is null
[12:34:32 WARN]:        at me.earthme.luminol.utils.LuminolWatchDog.runCheck(LuminolWatchDog.java:72)
[12:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[12:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[12:34:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[12:34:32 WARN]: Exception in thread "pool-48-thread-21" java.lang.NullPointerException: Cannot invoke "org.apache.commons.lang3.tuple.Pair.getLeft()" because the return value of "java.util.Map.get(Object)" is null
[12:34:32 WARN]:        at me.earthme.luminol.utils.LuminolWatchDog.runCheck(LuminolWatchDog.java:72)
[12:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[12:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[12:34:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[12:34:32 WARN]: Exception in thread "pool-48-thread-22" java.lang.NullPointerException: Cannot invoke "org.apache.commons.lang3.tuple.Pair.getLeft()" because the return value of "java.util.Map.get(Object)" is null
[12:34:32 WARN]:        at me.earthme.luminol.utils.LuminolWatchDog.runCheck(LuminolWatchDog.java:72)
[12:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[12:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[12:34:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[12:34:32 WARN]: Exception in thread "pool-48-thread-23" java.lang.NullPointerException: Cannot invoke "org.apache.commons.lang3.tuple.Pair.getLeft()" because the return value of "java.util.Map.get(Object)" is null
[12:34:32 WARN]:        at me.earthme.luminol.utils.LuminolWatchDog.runCheck(LuminolWatchDog.java:72)
[12:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[12:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[12:34:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[12:34:32 WARN]: Exception in thread "pool-48-thread-24" java.lang.NullPointerException: Cannot invoke "org.apache.commons.lang3.tuple.Pair.getLeft()" because the return value of "java.util.Map.get(Object)" is null
[12:34:32 WARN]:        at me.earthme.luminol.utils.LuminolWatchDog.runCheck(LuminolWatchDog.java:72)
[12:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[12:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[12:34:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[12:34:32 WARN]: Exception in thread "pool-48-thread-25" java.lang.NullPointerException: Cannot invoke "org.apache.commons.lang3.tuple.Pair.getLeft()" because the return value of "java.util.Map.get(Object)" is null
[12:34:32 WARN]:        at me.earthme.luminol.utils.LuminolWatchDog.runCheck(LuminolWatchDog.java:72)
[12:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[12:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[12:34:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[12:34:32 WARN]: Exception in thread "pool-48-thread-26" java.lang.NullPointerException: Cannot invoke "org.apache.commons.lang3.tuple.Pair.getLeft()" because the return value of "java.util.Map.get(Object)" is null
[12:34:32 WARN]:        at me.earthme.luminol.utils.LuminolWatchDog.runCheck(LuminolWatchDog.java:72)
[12:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[12:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[12:34:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[12:34:33 WARN]: Exception in thread "pool-48-thread-27" java.lang.NullPointerException: Cannot invoke "org.apache.commons.lang3.tuple.Pair.getLeft()" because the return value of "java.util.Map.get(Object)" is null
[12:34:33 WARN]:        at me.earthme.luminol.utils.LuminolWatchDog.runCheck(LuminolWatchDog.java:72)
[12:34:33 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[12:34:33 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[12:34:33 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[12:34:33 WARN]: Exception in thread "pool-48-thread-28" java.lang.NullPointerException: Cannot invoke "org.apache.commons.lang3.tuple.Pair.getLeft()" because the return value of "java.util.Map.get(Object)" is null
[12:34:33 WARN]:        at me.earthme.luminol.utils.LuminolWatchDog.runCheck(LuminolWatchDog.java:72)
[12:34:33 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[12:34:33 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[12:34:33 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[12:34:33 WARN]: Exception in thread "pool-48-thread-29" java.lang.NullPointerException: Cannot invoke "org.apache.commons.lang3.tuple.Pair.getLeft()" because the return value of "java.util.Map.get(Object)" is null
[12:34:33 WARN]:        at me.earthme.luminol.utils.LuminolWatchDog.runCheck(LuminolWatchDog.java:72)
[12:34:33 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[12:34:33 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[12:34:33 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[12:34:33 INFO]: [ChunkHolderManager] Saved 961 block chunks, 961 entity chunks, 0 poi chunks in world 'world' in 1.21s
[12:34:33 WARN]: Exception in thread "pool-48-thread-30" java.lang.NullPointerException: Cannot invoke "org.apache.commons.lang3.tuple.Pair.getLeft()" because the return value of "java.util.Map.get(Object)" is null
[12:34:33 WARN]:        at me.earthme.luminol.utils.LuminolWatchDog.runCheck(LuminolWatchDog.java:72)
[12:34:33 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[12:34:33 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[12:34:33 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[12:34:33 INFO]: [RegionShutdownThread] Saving chunks around region around chunk [0, 0] in world 'world_nether'
[12:34:33 WARN]: Exception in thread "pool-48-thread-31" java.lang.NullPointerException: Cannot invoke "org.apache.commons.lang3.tuple.Pair.getLeft()" because the return value of "java.util.Map.get(Object)" is null
[12:34:33 WARN]:        at me.earthme.luminol.utils.LuminolWatchDog.runCheck(LuminolWatchDog.java:72)
[12:34:33 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[12:34:33 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[12:34:33 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[12:34:33 INFO]: [ChunkHolderManager] Saved 49 block chunks, 49 entity chunks, 0 poi chunks in world 'world_nether' in 0.07s
[12:34:33 INFO]: [RegionShutdownThread] Saving chunks around region around chunk [0, 0] in world 'world_the_end'
[12:34:33 INFO]: [ChunkHolderManager] Saved 49 block chunks, 49 entity chunks, 0 poi chunks in world 'world_the_end' in 0.01s
[12:34:33 INFO]: [RegionShutdownThread] Saving players
[12:34:33 WARN]: Exception in thread "pool-48-thread-32" java.lang.NullPointerException: Cannot invoke "org.apache.commons.lang3.tuple.Pair.getLeft()" because the return value of "java.util.Map.get(Object)" is null
[12:34:33 WARN]:        at me.earthme.luminol.utils.LuminolWatchDog.runCheck(LuminolWatchDog.java:72)
[12:34:33 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[12:34:33 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[12:34:33 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[12:34:33 INFO]: Flushing Chunk IO
[12:34:33 INFO]: Closing Thread Pool
[12:34:33 INFO]: Closing Server

### 观测到的实际行为 Observed/Actual behavior

stop server

### 复现步骤 Steps/models to reproduce

stop server

### 插件与数据包列表。 Plugin and Datapack List.

![image](https://github.com/LuminolMC/Luminol/assets/70480001/da96ad70-57d8-4e22-bde6-5c79ed5e9b7e)

**Comment by MrHua269** [comment]
Try b8963f9862fa3c63bcaadb06e4707c6007a47077

**Comment by mani1232** [comment]
> Try [b8963f9](https://github.com/LuminolMC/Luminol/commit/b8963f9862fa3c63bcaadb06e4707c6007a47077)

```
====================================
[12:26:32] [pool-50-thread-1/ERROR]: ====================================
There is a single region that has no responding in 18 seconds!
If you believe this is a bug,please send it to github issue after checking your plugins!
Tick Region: Global Region
Thread Name: Region Scheduler Thread #3
Thread Id: 120
Is Suspend: false
Thread State: TIMED_WAITING
Thread Priority: 8
Thread Stack Trace:
		java.base/jdk.internal.misc.Unsafe.park(Native Method)
		java.base/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269)
		ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:514)
		java.base/java.lang.Thread.run(Thread.java:1583)

====================================
[12:26:37] [pool-50-thread-1/ERROR]: ====================================
There is a single region that has no responding in 23 seconds!
If you believe this is a bug,please send it to github issue after checking your plugins!
Tick Region: Global Region
Thread Name: Region Scheduler Thread #3
Thread Id: 120
Is Suspend: false
Thread State: TIMED_WAITING
Thread Priority: 8
Thread Stack Trace:
		java.base/jdk.internal.misc.Unsafe.park(Native Method)
		java.base/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269)
		ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:514)
		java.base/java.lang.Thread.run(Thread.java:1583)

====================================
[12:26:42] [pool-50-thread-1/ERROR]: ====================================
There is a single region that has no responding in 28 seconds!
If you believe this is a bug,please send it to github issue after checking your plugins!
Tick Region: Global Region
Thread Name: Region Scheduler Thread #3
Thread Id: 120
Is Suspend: false
Thread State: TIMED_WAITING
Thread Priority: 8
Thread Stack Trace:
		java.base/jdk.internal.misc.Unsafe.park(Native Method)
		java.base/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269)
		ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:514)
		java.base/java.lang.Thread.run(Thread.java:1583)

====================================
[12:26:43] [Region shutdown thread/INFO]: [RegionShutdownThread] Awaiting scheduler termination for 60s
[12:26:43] [Region shutdown thread/INFO]: [RegionShutdownThread] Scheduler halted
[12:26:43] [Region shutdown thread/INFO]: Stopping server
[12:26:43] [Region shutdown thread/INFO]: [spark] Disabling spark v1.10.60
[12:26:43] [Region shutdown thread/INFO]: [Lands] Disabling Lands v7.6.3
[12:26:43] [Region shutdown thread/INFO]: [Lands] Closing storage.
[12:26:43] [Region shutdown thread/INFO]: [Lands] Took 56 ms.
[12:26:43] [Region shutdown thread/INFO]: [CoreProtect] Disabling CoreProtect v22.4
[12:26:43] [Region shutdown thread/INFO]: [CoreProtect] Finishing up data logging. Please wait...
[12:26:44] [Region shutdown thread/INFO]: [CoreProtect] Success! Disabled CoreProtect v22.4
[12:26:44] [Region shutdown thread/INFO]: [FancyHolograms] Disabling FancyHolograms v2.3.0.82
[12:26:44] [Region shutdown thread/INFO]: [HuskHomes] Disabling HuskHomes v4.7
[12:26:44] [Region shutdown thread/INFO]: [HuskHomes] Successfully disabled HuskHomes v4.7
[12:26:44] [Region shutdown thread/INFO]: [SayanVanish] Disabling SayanVanish v1.2.1-SNAPSHOT-build.152-856ea41
[12:26:44] [Region shutdown thread/INFO]: [MoreFoWorld] Disabling MoreFoWorld v1.6.0
[12:26:44] [Region shutdown thread/INFO]: [CarbonChat] Disabling CarbonChat v3.0.0-SNAPSHOT+9cc5a2d
[12:26:44] [Region shutdown thread/INFO]: [AntiPopup] Disabling AntiPopup v8.1
[12:26:44] [Region shutdown thread/INFO]: [AntiPopup] Disabled PacketEvents.
[12:26:44] [Region shutdown thread/INFO]: [voicechat] Disabling voicechat v2.5.16
[12:26:44] [Region shutdown thread/INFO]: [GSit] Disabling GSit v1.9.5
[12:26:44] [Region shutdown thread/INFO]: [GSit] The plugin was successfully disabled.
[12:26:44] [Region shutdown thread/INFO]: [ZNPCsPlus] Disabling ZNPCsPlus v2.0.0-SNAPSHOT
[12:26:44] [Region shutdown thread/INFO]: [Chunky] Disabling Chunky v1.4.16
[12:26:44] [Region shutdown thread/INFO]: [SkinsRestorer] Disabling SkinsRestorer v15.0.15
[12:26:44] [Region shutdown thread/INFO]: [LuckPerms] Disabling LuckPerms v5.4.117
[12:26:44] [Region shutdown thread/INFO]: [LuckPerms] Starting shutdown process...
[12:26:44] [Region shutdown thread/INFO]: [LuckPerms] Closing storage...
[12:26:45] [Region shutdown thread/INFO]: [LuckPerms] Goodbye!
[12:26:45] [Region shutdown thread/INFO]: [ViaBackwards] Disabling ViaBackwards v5.0.2-SNAPSHOT
[12:26:45] [Region shutdown thread/INFO]: [floodgate] Disabling floodgate v2.2.3-SNAPSHOT (b109-49bd564)
[12:26:45] [Region shutdown thread/INFO]: [ViaVersion] Disabling ViaVersion v5.0.2-SNAPSHOT
[12:26:45] [Region shutdown thread/INFO]: [ViaVersion] ViaVersion is disabling, if this is a reload and you experience issues consider rebooting.
[12:26:45] [Region shutdown thread/INFO]: [TerraformGenerator] Disabling TerraformGenerator v16.1.0
[12:26:45] [Region shutdown thread/INFO]: [RegionShutdownThread] Halting chunk systems
[12:26:45] [Region shutdown thread/INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'new_world'
[12:26:45] [Region shutdown thread/INFO]: [ChunkHolderManager] Halted chunk system for world 'new_world'
[12:26:45] [Region shutdown thread/INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world'
[12:26:45] [Region shutdown thread/INFO]: [ChunkHolderManager] Halted chunk system for world 'world'
[12:26:45] [Region shutdown thread/INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world_nether'
[12:26:45] [Region shutdown thread/INFO]: [ChunkHolderManager] Halted chunk system for world 'world_nether'
[12:26:45] [Region shutdown thread/INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world_the_end'
[12:26:45] [Region shutdown thread/INFO]: [ChunkHolderManager] Halted chunk system for world 'world_the_end'
[12:26:45] [Region shutdown thread/INFO]: [RegionShutdownThread] Halted chunk systems
[12:26:45] [Region shutdown thread/INFO]: [RegionShutdownThread] Saving chunks around region around chunk [-1, 0] in world 'new_world'
[12:26:45] [Region shutdown thread/INFO]: [ChunkHolderManager] Saved 0 block chunks, 19 entity chunks, 0 poi chunks in world 'new_world' in 0.01s
[12:26:45] [Region shutdown thread/INFO]: [RegionShutdownThread] Saving chunks around region around chunk [0, 0] in world 'world'
[12:26:45] [Region shutdown thread/INFO]: [ChunkHolderManager] Saved 0 block chunks, 10 entity chunks, 0 poi chunks in world 'world' in 0.00s
[12:26:45] [Region shutdown thread/INFO]: [RegionShutdownThread] Saving chunks around region around chunk [0, 0] in world 'world_nether'
[12:26:45] [Region shutdown thread/INFO]: [ChunkHolderManager] Saved 1 block chunks, 7 entity chunks, 0 poi chunks in world 'world_nether' in 0.00s
[12:26:45] [Region shutdown thread/INFO]: [RegionShutdownThread] Saving chunks around region around chunk [-1121, -292] in world 'world_nether'
[12:26:46] [Region shutdown thread/INFO]: [ChunkHolderManager] Saved 1429 block chunks, 1429 entity chunks, 0 poi chunks in world 'world_nether' in 1.60s
[12:26:46] [Region shutdown thread/INFO]: [RegionShutdownThread] Saving chunks around region around chunk [0, 0] in world 'world_the_end'
[12:26:46] [Region shutdown thread/INFO]: [ChunkHolderManager] Saved 0 block chunks, 0 entity chunks, 0 poi chunks in world 'world_the_end' in 0.00s
[12:26:46] [Region shutdown thread/INFO]: [RegionShutdownThread] Saving players
[12:26:46] [Region shutdown thread/INFO]: Flushing Chunk IO
[12:26:46] [Region shutdown thread/INFO]: Closing Thread Pool
[12:26:46] [Region shutdown thread/INFO]: Closing Server
```

**Comment by MrHua269** [comment]
Try 1f881dd40992231debdf26b852dacf08a786c2d0

**Comment by mani1232** [comment]
> Try [1f881dd](https://github.com/LuminolMC/Luminol/commit/1f881dd40992231debdf26b852dacf08a786c2d0)

no, its not fixed
