### ISSUE TITLE
Plugin cannot load

### ISSUE THREAD

**Issue by Dg32z** [LuminolMC/Luminol#27]
### 服务端版本 LuminolMC Version

> ver [20:12:53 INFO]: Checking version, please wait... [20:12:53 INFO]: This server is running Luminol version 1.21.1-DEV-dev/1.21.1@7c312e7 (2024-08-17T05:31:51Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT) You are running the latest version Previous version: 1.21-54-f250ec0 (MC: 1.21)

### 预期的行为 Expected behavior

Starting org.bukkit.craftbukkit.Main
[20:20:46 INFO]: [bootstrap] Running Java 21 (Java HotSpot(TM) 64-Bit Server VM 21.0.3+7-LTS-152; Oracle Corporation null) on Windows 10 10.0 (amd64)
[20:20:46 INFO]: [bootstrap] Loading Luminol 1.21.1-DEV-dev/1.21.1@7c312e7 (2024-08-17T05:31:51Z) for Minecraft 1.21.1
[20:20:46 INFO]: [PluginInitializerManager] Initializing plugins...
[20:20:47 INFO]: [PluginInitializerManager] Initialized 5 plugins
[20:20:47 INFO]: [PluginInitializerManager] Bukkit plugins (5):
 - ChaosCore (1.0), LiteBans (2.15.1), LuckPerms (5.4.135), PlaceholderAPI (2.11.7-DEV-null), PlugManX (2.4.1)
[20:20:50 INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]

### 观测到的实际行为 Observed/Actual behavior

Starting org.bukkit.craftbukkit.Main
[20:11:03 INFO]: [bootstrap] Running Java 21 (Java HotSpot(TM) 64-Bit Server VM 21.0.3+7-LTS-152; Oracle Corporation null) on Windows 10 10.0 (amd64)
[20:11:03 INFO]: [bootstrap] Loading Luminol 1.21.1-DEV-dev/1.21.1@7c312e7 (2024-08-17T05:31:51Z) for Minecraft 1.21.1
[20:11:03 INFO]: [PluginInitializerManager] Initializing plugins...
[20:11:04 ERROR]: [DirectoryProviderSource] Error loading plugin: Cannot invoke "Object.toString()" because "o" is null
java.lang.NullPointerException: Cannot invoke "Object.toString()" because "o" is null
        at org.bukkit.plugin.PluginDescriptionFile.loadMap(PluginDescriptionFile.java:1247) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.PluginDescriptionFile.<init>(PluginDescriptionFile.java:349) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.create(SpigotPluginProviderFactory.java:81) ~[luminol-1.21.1.jar:1.21.1-DEV-7c312e7]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.create(SpigotPluginProviderFactory.java:28) ~[luminol-1.21.1.jar:1.21.1-DEV-7c312e7]
        at io.papermc.paper.plugin.provider.type.PluginFileType.getConfig(PluginFileType.java:78) ~[luminol-1.21.1.jar:1.21.1-DEV-7c312e7]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:90) ~[luminol-1.21.1.jar:1.21.1-DEV-7c312e7]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:52) ~[luminol-1.21.1.jar:1.21.1-DEV-7c312e7]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:17) ~[luminol-1.21.1.jar:1.21.1-DEV-7c312e7]
        at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:15) ~[luminol-1.21.1.jar:1.21.1-DEV-7c312e7]
        at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:113) ~[luminol-1.21.1.jar:1.21.1-DEV-7c312e7]
        at net.minecraft.server.Main.main(Main.java:123) ~[luminol-1.21.1.jar:1.21.1-DEV-7c312e7]
        at io.papermc.paper.PaperBootstrap.boot(PaperBootstrap.java:21) ~[luminol-1.21.1.jar:1.21.1-DEV-7c312e7]
        at org.bukkit.craftbukkit.Main.main(Main.java:281) ~[luminol-1.21.1.jar:1.21.1-DEV-7c312e7]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[20:11:04 INFO]: [PluginInitializerManager] Initialized 5 plugins
[20:11:04 INFO]: [PluginInitializerManager] Bukkit plugins (5):

### 复现步骤 Steps/models to reproduce

我使用一个BukkitAPI/sqlite-jdbc/tomcat-embed-websocket/fastjson 来实现的工具插件,但是在PluginInitializerManager时报错，插件也没有正常启动,也没有报错出我的插件出现任何问题

### 插件与数据包列表。 Plugin and Datapack List.

> pl
[20:18:07 INFO]: Server Plugins (4):
[20:18:07 INFO]: Bukkit Plugins:
[20:18:07 INFO]:  - LiteBans, LuckPerms, PlaceholderAPI, PlugManX

### 更多详细信息。 The more information.

[latest.log](https://github.com/user-attachments/files/16644797/latest.log)

**Comment by Dg32z** [comment]
my iessue ):
