### ISSUE TITLE
Error crash 

### ISSUE THREAD

**Issue by Thanhori** [LuminolMC/Luminol#30]
### 服务端版本 LuminolMC Version

 @github-actions github-actions  1.20.4-ec99488  ec99488 LightingLuminol 1.20.4 - ec99488

### 预期的行为 Expected behavior

[12:00:41 INFO]: [RegionShutdownThread] Awaiting scheduler termination for 60s
Bạn đã gửi
[12:00:41] [Region Scheduler Thread #2/ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Region #990 centered at chunk [207, -216] in world 'world' failed to tick:
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.Entity.dH()" because "entity" is null
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1637) ~[lightingluminol-1.20.4.jar:git-Luminol-"5dc57c8"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:436) ~[lightingluminol-1.20.4.jar:git-Luminol-"5dc57c8"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[lightingluminol-1.20.4.jar:git-Luminol-"5dc57c8"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[lightingluminol-1.20.4.jar:git-Luminol-"5dc57c8"]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[12:00:41] [Region shutdown thread/INFO]: [RegionShutdownThread] Awaiting scheduler termination for 60s
[12:00:41] [Region shutdown thread/INFO]: [RegionShutdownThread] Scheduler halted

### 观测到的实际行为 Observed/Actual behavior

[12:00:41 INFO]: [RegionShutdownThread] Awaiting scheduler termination for 60s
Bạn đã gửi
[12:00:41] [Region Scheduler Thread #2/ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Region #990 centered at chunk [207, -216] in world 'world' failed to tick:
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.Entity.dH()" because "entity" is null
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1637) ~[lightingluminol-1.20.4.jar:git-Luminol-"5dc57c8"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:436) ~[lightingluminol-1.20.4.jar:git-Luminol-"5dc57c8"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[lightingluminol-1.20.4.jar:git-Luminol-"5dc57c8"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[lightingluminol-1.20.4.jar:git-Luminol-"5dc57c8"]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[12:00:41] [Region shutdown thread/INFO]: [RegionShutdownThread] Awaiting scheduler termination for 60s
[12:00:41] [Region shutdown thread/INFO]: [RegionShutdownThread] Scheduler halted

### 复现步骤 Steps/models to reproduce

[12:00:41 INFO]: [RegionShutdownThread] Awaiting scheduler termination for 60s
Bạn đã gửi
[12:00:41] [Region Scheduler Thread #2/ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Region #990 centered at chunk [207, -216] in world 'world' failed to tick:
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.Entity.dH()" because "entity" is null
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1637) ~[lightingluminol-1.20.4.jar:git-Luminol-"5dc57c8"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:436) ~[lightingluminol-1.20.4.jar:git-Luminol-"5dc57c8"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[lightingluminol-1.20.4.jar:git-Luminol-"5dc57c8"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[lightingluminol-1.20.4.jar:git-Luminol-"5dc57c8"]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[12:00:41] [Region shutdown thread/INFO]: [RegionShutdownThread] Awaiting scheduler termination for 60s
[12:00:41] [Region shutdown thread/INFO]: [RegionShutdownThread] Scheduler halted

### 插件与数据包列表。 Plugin and Datapack List.

none

### 更多详细信息。 The more information.

n

**Comment by MrHua269** [comment]
Do not report the issues of LightingLuminol to Luminol which LightingLuminol is totally unstable now.

**Comment by MrHua269** [comment]
And we don't suggest to use that
