### ISSUE TITLE
Entity threw exception at world:17.5,-17.0,-31.5

### ISSUE THREAD

**Issue by yvmouX** [LuminolMC/Luminol#33]
### 服务端版本 LuminolMC Version

Luminol 1.21.4 - ea34494

### 预期的行为 Expected behavior

fix 

### 观测到的实际行为 Observed/Actual behavior

暂无发现实际负面影响

### 复现步骤 Steps/models to reproduce

似乎错误发生在尝试获取一个Entity（实体）的光照级别时。

### 插件与数据包列表。 Plugin and Datapack List.

zMenu
无Datapack 
![1](https://img-cdn.yvmou.cn/pigo/202412140021640.png)

### 更多详细信息。 The more information.

[23:59:25 INFO]: Done (3.007s)! For help, type "help"
[23:59:25 INFO]: Initialising world 'world' before it can be ticked...
[23:59:25 INFO]: Initialised world 'world'
[23:59:25 INFO]: Initialising world 'world_nether' before it can be ticked...
[23:59:25 INFO]: Initialised world 'world_nether'
[23:59:26 INFO]: Initialising world 'world_the_end' before it can be ticked...
[23:59:26 INFO]: Initialised world 'world_the_end'
[23:59:26 INFO]: [zMenu v1.0.3.6] No update available.
[00:03:40 INFO]: UUID of player yvmou_ is 9d0bfed4-ef55-3908-a4f2-8f3b0fe98d63
[00:03:41 INFO]: yvmou_ joined the game
[00:03:41 INFO]: yvmou_[/127.0.0.1:2381] logged in with entity id 19 at ([world]4.5, 63.0, -0.5)
> op yvmou_
[00:03:50 INFO]: Made yvmou_ a server operator
[00:03:56 INFO]: yvmou_ issued server command: /zmenu
[00:06:51 INFO]: yvmou_ issued server command: /zm editor
[00:07:48 ERROR]: Entity threw exception at world:17.5,-17.0,-31.5
java.lang.NullPointerException: Cannot invoke "net.minecraft.core.BlockPos.getX()" because "pos" is null
        at net.minecraft.world.level.LevelReader.getMaxLocalRawBrightness(LevelReader.java:184) ~[luminol-1.21.4.jar:1.21.4-DEV-ea34494]
        at net.minecraft.world.level.LevelReader.getMaxLocalRawBrightness(LevelReader.java:180) ~[luminol-1.21.4.jar:1.21.4-DEV-ea34494]
        at net.minecraft.world.level.LevelReader.getLightLevelDependentMagicValue(LevelReader.java:129) ~[luminol-1.21.4.jar:1.21.4-DEV-ea34494]
        at net.minecraft.world.entity.Entity.getLightLevelDependentMagicValue(Entity.java:2245) ~[luminol-1.21.4.jar:1.21.4-DEV-ea34494]
        at net.minecraft.world.entity.Mob.isSunBurnTick(Mob.java:1776) ~[luminol-1.21.4.jar:1.21.4-DEV-ea34494]
        at net.minecraft.world.entity.monster.Zombie.aiStep(Zombie.java:243) ~[luminol-1.21.4.jar:1.21.4-DEV-ea34494]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3363) ~[luminol-1.21.4.jar:1.21.4-DEV-ea34494]
        at net.minecraft.world.entity.Mob.tick(Mob.java:453) ~[luminol-1.21.4.jar:1.21.4-DEV-ea34494]
        at net.minecraft.world.entity.monster.Zombie.tick(Zombie.java:236) ~[luminol-1.21.4.jar:1.21.4-DEV-ea34494]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1390) ~[luminol-1.21.4.jar:1.21.4-DEV-ea34494]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:1539) ~[luminol-1.21.4.jar:1.21.4-DEV-ea34494]
        at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:845) ~[luminol-1.21.4.jar:1.21.4-DEV-ea34494]
        at io.papermc.paper.threadedregions.RegionizedWorldData.forEachTickingEntity(RegionizedWorldData.java:601) ~[luminol-1.21.4.jar:1.21.4-DEV-ea34494]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:818) ~[luminol-1.21.4.jar:1.21.4-DEV-ea34494]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:2021) ~[luminol-1.21.4.jar:1.21.4-DEV-ea34494]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1829) ~[luminol-1.21.4.jar:1.21.4-DEV-ea34494]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[luminol-1.21.4.jar:1.21.4-DEV-ea34494]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:418) ~[luminol-1.21.4.jar:1.21.4-DEV-ea34494]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:546) ~[concurrentutil-0.0.2.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[00:10:41 INFO]: yvmou_ was slain by Zombie
[00:13:18 INFO]: yvmou_ issued server command: /zmenu download https://zmenu.dev/d/1755
[00:13:33 INFO]: yvmou_ issued server command: /gamemode creative
[00:13:33 INFO]: [yvmou_: Set own game mode to Creative Mode]
[00:13:43 INFO]: yvmou_ issued server command: /zmenu open zmenu:pro_inventory
[00:13:58 INFO]: yvmou_ issued server command: /zm reload
[00:13:58 INFO]: [zMenu v1.0.3.6] plugins\zMenu\patterns\pattern_example.yml loaded successfully !
[00:13:58 INFO]: [zMenu v1.0.3.6] plugins\zMenu\inventories\advanced_inventory.yml loaded successfully !
[00:13:58 INFO]: [zMenu v1.0.3.6] plugins\zMenu\inventories\bank.yml loaded successfully !
[00:13:58 INFO]: [zMenu v1.0.3.6] plugins\zMenu\inventories\basic_inventory.yml loaded successfully !
[00:13:58 INFO]: [zMenu v1.0.3.6] plugins\zMenu\inventories\example_punish.yml loaded successfully !
[00:13:58 INFO]: [zMenu v1.0.3.6] plugins\zMenu\inventories\pro_inventory.yml loaded successfully !
[00:13:58 INFO]: [zMenu v1.0.3.6] plugins\zMenu\website\inventories.yml loaded successfully !
[00:13:58 INFO]: [zMenu v1.0.3.6] Command /basic_command successfully register.
[00:13:58 INFO]: [zMenu v1.0.3.6] Command /advanced_command successfully register.
[00:13:58 INFO]: [zMenu v1.0.3.6] Command /pro_command successfully register.
[00:13:58 INFO]: [zMenu v1.0.3.6] Command /openbook successfully register.
[00:13:58 INFO]: [zMenu v1.0.3.6] Command /punish successfully register.
[00:14:03 INFO]: yvmou_ issued server command: /zm open zmenu:bank
[00:14:32 INFO]: yvmou_ issued server command: /zm editor

**Comment by MrHua269** [comment]
emmm，能够在最新版复现吗，目前看src应该是不会导致这个NPE的（）

**Comment by MrHua269** [comment]
试试 https://github.com/LuminolMC/Luminol/commit/bb144df37bba60152eb01b1e1c0decb3a9102c06()
